### PR TITLE
Fix Reset deadlock/problems with bytes.Buffer

### LINKED ISSUE #115: zstd: Decoder.Reset deadlock
Starting with commit 50006fb, my simple zstd test program started deadlocking. The `bytes.Buffer` I pass to `Decoder.Reset` is less than 1MB, which is what that commit optimizes for.

Thanks for your efforts on a pure-go zstd implementation!

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan send]:
github.com/klauspost/compress/zstd.(*Decoder).Reset(0xc0000f8000, 0x114cc60, 0xc00066c030, 0x7dd3b, 0x10c52)
	/Users/aaronb/go/src/github.com/klauspost/compress/zstd/decoder.go:171 +0x1f6
main.zstdCompress(0xc000128000, 0x10c52, 0x1fe00, 0xc00009bbb0, 0x105adfc, 0x114cc80)
	/Users/aaronb/zstd.go:168 +0x1c7
main.compress(0xc000128000, 0x10c52, 0x1fe00, 0xc000016d80, 0x1, 0x1, 0x0, 0x0, 0x1)
	/Users/aaronb/zstd.go:102 +0x6f
main.main()
	/Users/aaronb/zstd.go:57 +0x23f

goroutine 4 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0000922c0)
	/Users/aaronb/go/src/github.com/klauspost/compress/zstd/blockdec.go:188 +0x120
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aaronb/go/src/github.com/klauspost/compress/zstd/blockdec.go:106 +0x155

goroutine 7 [chan receive]:
github.com/klauspost/compress/zstd.(*Decoder).startStreamDecoder(0xc0000f8000, 0xc00005a360)
	/Users/aaronb/go/src/github.com/klauspost/compress/zstd/decoder.go:379 +0x272
created by github.com/klauspost/compress/zstd.(*Decoder).Reset
	/Users/aaronb/go/src/github.com/klauspost/compress/zstd/decoder.go:154 +0x422
exit status 2
```

Here is a snippet of my simple test program. `zstdCompress` is called in a loop on different inputs. The deadlock is occurring on the line with `zstdReader.Reset(buf)`.

```
type compressedResult struct {
	size           int
	compressTime   time.Duration
	decompressTime time.Duration
}

var zstdWriter, _ = zstd.NewWriter(nil, zstd.WithEncoderConcurrency(1))
var zstdReader, _ = zstd.NewReader(nil, zstd.WithDecoderConcurrency(1))

func zstdCompress(msg []byte) compressedResult {
	var r compressedResult
	buf := &bytes.Buffer{}
	t1 := time.Now()
	zstdWriter.Reset(buf)
	if _, err := zstdWriter.Write(msg); err != nil {
		panic(err)
	}
	if err := zstdWriter.Close(); err != nil {
		panic(err)
	}
	r.compressTime = time.Since(t1)
	r.size = len(buf.Bytes())

	t2 := time.Now()
	if err := zstdReader.Reset(buf); err != nil {
		panic(err)
	}
	out, err := ioutil.ReadAll(zstdReader)
	if err != nil {
		panic(err)
	}
	r.decompressTime = time.Since(t2)

	if !bytes.Equal(msg, out) {
		fmt.Println("bad decompress")
	}

	return r
}
```

### PR DESCRIPTION
**Pull request by klauspost**
Fix problem with byte buffer shortcut not returning correct data when input is a small *bytes.Buffer and add test for these.

Fixes #115

### CODE REVIEW

**Comment by aaronbee** [comment]
This fixes my issue. Thanks!

File: zstd/decoder_test.go [hunk 1]
```diff
@@ -198,6 +198,71 @@ func TestDecoderRegression(t *testing.T) {
...
+			t.Fatal("Decoded does not match")
+		}
+	}
+	// Test without WriterTo interface support.
+	for i := 0; i < 3; i++ {
+		err = dec.Reset(bytes.NewBuffer(dst))
+		if err != nil {
+			t.Fatal(err)
+		}
+		decoded, err := ioutil.ReadAll(ioutil.NopCloser(dec))
```
Comment (aaronbee) [inline zstd/decoder_test.go]: I don't believe the `NopCloser` is necessary here. `ioutil.ReadAll` takes in just a `io.Reader` and does not attempt to `Close`.

Comment (klauspost) [reply zstd/decoder_test.go]: The wrapping is to make sure we don't support the io.WriterTo interface.
