### PR TITLE
s2: Fix huge block overflow

### LINKED ISSUE #778: s2.Encode a large value panic
I'd wrote a unit test with s2.Encode, found that a panic on such scenario as following
```
v := make([]byte, math.MaxInt32)
if s2.MaxEncodedLen(len(v)) != -1 {
	s2.Encode(nil, v)
}
```
the stack is 
```runtime: g 6: unexpected return pc for github.com/klauspost/compress/s2.encodeBlockAsm called from 0x5000500050005```

### PR DESCRIPTION
**Pull request by klauspost**
Fixes crash on encoding single blocks close to or above 2147483647 bytes on amd64.

Fixes #778

Use unsigned compares in assembly.

Lowers the maximum block size on 32 bit platforms. Realistically you wouldn't be able to get close to it anyway.

### CODE REVIEW

File: s2/encode.go [hunk 1]
```diff
@@ -366,7 +369,14 @@ const MaxBlockSize = math.MaxUint32 - binary.MaxVarintLen32 - 5
 // 32 bit platforms will have lower thresholds for rejecting big content.
 func MaxEncodedLen(srcLen int) int {
 	n := uint64(srcLen)
-	if n > 0xffffffff {
+	if intReduction == 1 {
```
Comment (greatroar) [inline s2/encode.go:372]: Isn't it more obvious to check whether math/bits.UintSize == 32?

Comment (klauspost) [reply s2/encode.go:372]: Ends up with the same. Potato/Potâto
